# Generated by Django 5.0.6 on 2024-06-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0003_brand_carbrand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarBrand',
            new_name='CarModel',
        ),
    ]
